### PR TITLE
new NuGet 1.0.1

### PR DESCRIPTION
**Pull request by vslee**
- added Coincheck and UPbit to README.md

### CODE REVIEW

**Review by jjxtra — APPROVED** [review]
Tip jar offer is still on the table... :)

**Comment by vslee** [comment]
I appreciate the offer! What might be helpful is if you could look into moving this ES repo either into the DigitalRuby org or a new separate org. Then I can start looking into things like preview daily builds and SourceLink. Maybe even one day we can get it accepted into the .NET foundation.

**Comment by jjxtra** [comment]
I can move it to digital ruby

**Comment by vslee** [comment]
Great!

**Pull request merged**
