### PR TITLE
Adding market orders to those that support it

### PR DESCRIPTION
**Pull request by Ofekw**

### CODE REVIEW

**Comment by jjxtra** [comment]
Looks great, just want to verify you have tested both limit and market order on each exchange that was modified.

**Comment by Ofekw** [comment]
I don't actually have access all of these. I can test Binance, Gdax and Kraken, but would need help with the others. Will comment back once verified. 

I followed their individual api docs - _we should be good_

**Comment by jjxtra** [comment]
The order type names match case insensitive - I would recommend a double check and make it match case sensitive. You can use ToUpperInvariant or ToLowerInvariant after the to string for those exchanges that don't use pascal casing but have uppercased or lowercased the whole thing.

**Comment by jjxtra** [comment]
Looks good now, made a few tweaks, namely Bitfinex wants "exchange limit" or "exchange market". Other than that good to go. Thanks for submitting the pull request!

**Comment by Ofekw** [comment]
Thank you for this awesome library! Expect more PRs soon!

I was a little confused by ther Bitfinex api docs, cheers for that!

**Comment by jjxtra** [comment]
Thank you! Looking forward to the goodies!

-- Jeff

**Pull request merged**
