### PR TITLE
new nuget 0.6.0.3

### PR DESCRIPTION
**Pull request by vslee**

### CODE REVIEW

**Comment by jjxtra** [comment]
Just as an FYI visual studio auto-generates a .nuspec without the summary tag. I had been manually adding it to the .nuspec in the nuget archive. But this looks good.

**Comment by vslee** [comment]
Ok, I will add the summary tag manually next time

**Comment by vslee** [comment]
Looks like the summary tag is now deprecated: https://github.com/dotnet/project-system/issues/2937

**Comment by vslee** [comment]
Although, I did copy the summary tag for 0.6.1 for now

**Pull request merged**
