### PR TITLE
Move to netstandard2.0

### LINKED ISSUE #477: Target netcoreapp2.0
As discussed in https://github.com/jjxtra/ExchangeSharp/pull/475#discussion_r342729770 we could start using `netstandard20` as a base runtime for this package and _maybe_ drop the overlapping support for `net472`.

### PR DESCRIPTION
**Pull request by johnnyasantoss**
- Fixes #477 
- Makes the default target `netstandard2.0`
- Move files into a more simplified structure
   - image
- Moves the winforms dependency to a separate package (even though I could not find where it is being used)
- Remove old files like `App.config` and `packages.config` (the first was a copy lying around in the root of the project and the second is not longer used)
- ~Does not change any `csharp` code~ (Changes were made to `Logger` and `ExchangePoloniexAPI` to use a new form of accessing embedded resources)

### CODE REVIEW

**Comment by johnnyasantoss** [comment]
Everything still working just fine :)

image

**Comment by johnnyasantoss** [comment]
Now, the only thing left to do is to fix this (given that `HAS_WINDOWS_FORMS` will never be defined):

https://github.com/jjxtra/ExchangeSharp/blob/ee8e4d13a78025fbb73cddda4e133fde858e637b/src/ExchangeSharp/API/Common/BaseAPI.cs#L257-L283

**Comment by jjxtra** [comment]
Probably we can boot that piece of code and move it into the win forms project with a note.

**Comment by jjxtra** [comment]
Thanks for all your work on this, I appreciate your attention to detail and I think the new organization structure will be very good.

**Comment by jjxtra** [comment]
@johnnyasantoss I made you a contributor by the way, appreciate you dedicating so much time to this project.

**Comment by johnnyasantoss** [comment]
> @johnnyasantoss I made you a contributor by the way, appreciate you dedicating so much time to this project.

Thank you! :)
I'll try to keep helping as much as I can

**Comment by johnnyasantoss** [comment]
Rebased!
Please take another look :) @jjxtra @vslee

**Comment by jjxtra** [comment]
Thanks for the rebase! Typically I always do squash and merge, but if it helps you to manager your commits before merge that's awesome :)

**Comment by johnnyasantoss** [comment]
I also prefer squashing the PRs. It makes the git commit history more consistent.

**Comment by vslee** [comment]
The changes in this PR cover so much code that by merging the two other PRs, it created additional conflicts. Can you rebase again?

**Comment by johnnyasantoss** [comment]
Yep, it moves basically every file in the solution, so it can be a bit cumbersome to have it updated.

**Comment by johnnyasantoss** [comment]
@vslee done :smiley:

**Comment by johnnyasantoss** [comment]
@vslee There are some weird files in the root folder. I just saw.
I'll send a new PR to fix it immediately. We need a CI asap to stop things like this from happening :see_no_evil:

**Comment by vslee** [comment]
No worries, part of the dev process

**Pull request merged**
