### PR TITLE
Added CryptopiaExchangeAPI

### PR DESCRIPTION
**Pull request by BobDeCuir**
Check comments in code.

### CODE REVIEW

**Comment by BobDeCuir** [comment]
I'll be doing a single pull request per new Exchange. This will make it easier to verify.

**Comment by jjxtra** [comment]
What is ExchangeTemplateAPI?

**Comment by BobDeCuir** [comment]
That's not supposed to be in there. I use it as a Template for adding new Exchanges. I told git to ignore on the push, but it didn't.

**Comment by BobDeCuir** [comment]
Did you need me to create a new pull request without the .git additions? All that is needed is the ExchangeCryptopiaAPI.cs file and the update to ExchangeNames. 

I have other exchanges I can add after this is merged.

**Comment by jjxtra** [comment]
Yea let's just do a new one without the .git and template api.

**Pull request closed without merging**
