### PR TITLE
Added OnGetTickersWebSocket implementation to ExchangeKucoinAPI

### PR DESCRIPTION
**Pull request by superhappychris**
Also added the ability to specify specific ticker symbols when using the tickers websocket.

### CODE REVIEW

**Comment by jjxtra** [comment]
params string[] symbols will not be null if it is left off entirely, we should check that ```params == null || params.Length == 0```

**Comment by superhappychris** [comment]
ah yes, good catch! I've just checked in a fix for that.

**Comment by superhappychris** [comment]
Whoops! Didn't mean to close the pull request!

**Comment by superhappychris** [comment]
@jjxtra this should be good to go now.  Is there something else you want me to change before you merge this in?

**Pull request merged**
