### PR TITLE
Implement websockets for Bittrex GetTickersWebSocket

### PR DESCRIPTION
**Pull request by bichuga**
Using https://github.com/JKorf/Bittrex.Net to handle both the signalR interface as well as cloudflare ddos protection. (MIT license)

### CODE REVIEW

**Comment by jjxtra** [comment]
Can you move the tests into the web socket test function in the console tests file? Then put the console main back to the way it was :)

**Comment by bichuga** [comment]
Yes of course. Just wanted to show that this actually worked

**Comment by jjxtra** [comment]
I switched to return IDisposable, more appropriate since the only purpose of the return value is to close the web socket. That should allow you to wrap Bittrex.net inside of an IDisposable, if it doesn't already implement it.

**Comment by bichuga** [comment]
Alright this is ready to go.

**Comment by jjxtra** [comment]
I think the only change I would want is that the ValueOrDefault calls use the ConvertInvariant<decimal> calls, to be consistant with the rest of the framework.

**Comment by jjxtra** [comment]
Ok if there is nothing else I will give this a merge and quick test. Let me know!

**Comment by bichuga** [comment]
Let 'er rip

**Comment by jjxtra** [comment]
Thanks for doing the work for this, your time is very much appreciated. Good luck on your trading!

**Pull request merged**
