### PR TITLE
Updated Getcandles, placeorder, getorderdetails for kucoin

### PR DESCRIPTION
**Pull request by kcabrera99**

### CODE REVIEW

**Comment by jjxtra** [comment]
Please revert ExchangeSharpConsole_Orders.cs

**Comment by vslee** [comment]
I tried it and it seems to work. I ran GetOpenOrderDetailsAsync() and it showed the order details. Which call wasn't working for you. Or did you figure it out.

**Comment by vslee** [comment]
Also, as @jjxtra mentioned, please revert ExchangeSharpConsole_Orders.cs. Furthermore, your dev key has been exposed by this PR. So go immediately on KuCoin and revoke the dev key listed so no one can hack your account.

**Comment by vslee** [comment]
Oh, I see your post on issue #350 where you said you already got it working

**Comment by kcabrera99** [comment]
I forgot I modified that file. I will revert that now and I revoked the key.

**Comment by jjxtra** [comment]
Thanks for taking the time!

**Pull request merged**
