### PR TITLE
Updating binance get tickers

### PR DESCRIPTION
**Pull request by Peixer**
# Changes
- Updating Binance GetTicker, to nomarlize symbol before request.
- Updating Bitfinex exchange GetAmounts, adding new parameter to choose wallet.

### CODE REVIEW

**Comment by jjxtra** [comment]
Looks like there are conflicts. You should pull latest and re-sync. Normalize symbol is gone and not necessary in 99% of cases.

**Comment by Peixer** [comment]
this change was necessary in my application, that is in production mode.

**Comment by jjxtra** [comment]
OnGetTickerAsync will have already had NormalizeMarketSymbol called. Do not call OnGetTickerAsync directly, call GetTickerAsync.

**Comment by Peixer** [comment]
Left this change
- Updating Bitfinex exchange GetAmounts, adding new parameter to choose wallet.

**Pull request merged**
