### PR TITLE
NDAX: added Trade stream (websocket)

### PR DESCRIPTION
**Pull request by vslee**
- could not figure out how to use the JSON deserialization as the trades are returned as arrays (@Kukks if you know how...?)
- created custom NDAXTrade subclass w/ additional properties
- fixed BaseUrlWebSocket
- account for null or missing marketSymbols param
- store instrumentId in MarketSymbol.AltMarketSymbol
- log errors in Trade and Ticker streams
- [affects all exchanges] fixed bug in ExchangeAPIExtensions.ParseTradeComponents<T>() where IsBuy flag was not being set

### CODE REVIEW

**Comment by Kukks** [comment]
Trades response:
```
[
{
{
“OMSId”: 0,
“TradeID”: 0,
“ProductPairCode”: 0,
“Quantity”: 0,
“Price”: 0,
“Order1”: 0,
“Order2”: 0,
“TradeTime”: “0001-01-01T05:00:00Z”,
“Direction”: {
“Options”: [
“NoChange”,
“UpTick”,
“DownTick”
]
},
“TakerSide”: 0,
“Side1AccountId”: 0,
“Side2AccountId”: 0,
“Order1Side”: {
“Options”: [
“Buy”,
“Sell”,
“Short”,
“Unknown”
]
},

“Order2Side”: {
“Options”: [
Buy”,
“Sell”,
“Short”,
“Unknown”

]
},

“BlockTrade”: false, “Order1ClientId”: 0,
“Order2ClientId”: 0,
},
}
]
```

**Comment by vslee** [comment]
Yes, I originally created the JSON deserialization object ExchangeNDAXAPI.TradeData according to their docs. However, when I looked at the actual JSON being returned, it was `[[1510719222970.21,6943.51,6890.27,6898.41,6891.16,0,6890.98,6891.98,1, 1510718681956.34]]`. Thus, I reverted to using the parsing in ExchangeAPIExtensions. This works, but I figured you might know how to use the JSON deserialization, which would likely be shorter (code wise).

**Comment by jjxtra** [comment]
Is this ready to merge?

**Comment by vslee** [comment]
Yep

**Pull request merged**
