### PR TITLE
[UNTESTED] [Binance] sapi endpoint, cleanup

### LINKED ISSUE #654: [Binance] Withdrawal endpoint deprecated
https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269

### PR DESCRIPTION
**Pull request by bezysoftware**
My attempt at refactoring Binance API, moving some method to use `sapi/v1` e.g. https://binance-docs.github.io/apidocs/spot/en/#withdraw-user_data

Unfortunately sapi isn't available on testnet and mainnet requires KYC, therefor I couldn't test it live. If anyone would be willing to share their API Token / Secret with me I could test + make fixes

Resolves #654

### CODE REVIEW

**Comment by vslee** [comment]
I don't have a Binance myself. So it might be hard to find a volunteer for keys. 
One option is: If we merge this now, would @jdx-john be willing to test this out next week after we release the next NuGet?

**Comment by jdx-john** [comment]
I have a Binance account but haven't set up an API key (however they implement this). I might be able to test but since I have holdings there I won't share my key for obvious reasons :)

I thought you could create a Binance account without having to get properly verified (with limits on what you can do) which might be sufficient for basic testing. @bezysoftware I am a little confused when you say you cannot test - are you working on Binance API but you are not a Binance user yourself?! Seems extremely generous of you if so :)

**Comment by bezysoftware** [comment]
You can create a Binance account, but cannot create the API keys without Intermediate verification ( https://www.binance.com/en/support/announcement/654c092a2a2347bdb5ccd6faa0c6c039 ).

I have an account and have been trading there for some time, but they seem to be restricting the usage a lot. So I will not be personally using it anymore but I am working on an OSS project which lets people pick an exchange and periodically buy small bitcoin amounts ( https://github.com/bezysoftware/autosats ). 

I though about creating a subaccount (which would have isolated funds) but it seems those need to be KYC verified as well :( so it doesn't really help

**Comment by jdx-john** [comment]
Thanks for clarifying @bezysoftware. I went through intermediate verification recently so I should be able to test - I currently use Kraken but plan to work with Binance later as well.

Are there any formal tests or are we talking user tests? Would using the Console app provide enough coverage if so?

**Review by vslee — APPROVED** [review]
No formal tests. But looks like @bezysoftware added console app functionality so you will be able to test using that.
Thanks for volunteering, I will merge this now.

**Comment by bezysoftware** [comment]
@jdx-john 

Console app should be fine, I added 3 more options (`currencies`, `withdraw` and `deposit-address`) to cover the changes, here's what should be run:

```
currencies -e Binance
withdraw -e Binance -a 0.01 -c BTC -d <your address>
deposit-address -e Binance -c BTC 
```

possibly a `buy` option to make sure we didn't break anything
`buy -e Binance -s BTCUSD -a 20 --order-type Limit --price 40000`

Note on the withdrawal, those should be done in batches, when I was testing them on Bitstamp / Bitfinex I could go to their website and cancel the created withdrawal request before it actually went through

**Comment by bezysoftware** [comment]
@jdx-john Did you get a change to test it?
@vslee Are you planning publishing the nuget package?

**Comment by vslee** [comment]
Not yet, waiting for two more things:
I have another PR almost ready to submit.
Plumbly indicated that he is almost ready to submit his PR here #634

**Comment by vslee** [comment]
Those have been merged. I have one more PR and then I will release the NuGet tomorrow.

**Comment by vslee** [comment]
NuGet v0.9.0 has now be released

**Comment by jdx-john** [comment]
Apologies I've not yet had the chance to test, work and other projects taking a lot of time!

**Pull request merged**
