### PR TITLE
Nonce generation

### PR DESCRIPTION
**Pull request by espirulina**
Multiply by 10 - Fixes different Time-zones issue

### CODE REVIEW

**Comment by jjxtra** [comment]
The nonce uses DateTime.UtcNow and *should* be unaffected by time zones. I'm worried that this is simply a hack to work around the underlying problem, which may re-appear. Is it possible to remove the * 10 and record your screen and debug through the code and post a video of the problem?

**Comment by espirulina** [comment]
image

**Comment by jjxtra** [comment]
The first number has 19 digits, the second 18. Does this error happen if
you re-generate new API keys?

-- Jeff

**Comment by espirulina** [comment]
@jjxtra Thanks ! Is the above picture enough, or you really need a video ?

**Comment by jjxtra** [comment]
Picture is fine. Does it work if you generate new API keys?

-- Jeff

**Comment by espirulina** [comment]
thanks @jjxtra ! It worked ! My guess is that somehow Keys generated before Summer time change (last sunday) might lead to wrong generation of bounces after that event. Does this make sense in your opinion ? :/ Take care !

**Comment by jjxtra** [comment]
I'm not sure this is the problem. I have API keys from several months ago
on Poloniex and they work fine.

-- Jeff

**Pull request closed without merging**
